#!/bin/bash

num=0
while [ $num -le 25 ]
do
#rm InpOutUg$num
	while read line;
	do	

		if [ "$line" = "In" ]
		then 
			echo "Out" >> ./Inputfolder/InpOutUg$num
		else
			echo $line >> ./Inputfolder/InpOutUg$num
		fi
	done < ./Inputfolder/InpInUg$num
((num++))
done
