#!/bin/bash

num=0
while [ $num -le 25 ]
do
#rm InpOutGr$num
	while read line;
	do	
	
		if [ "$line" = "UG" ]
		then 
			echo "GR" >> InpOutGr$num
		else
			echo $line >> InpOutGr$num
		fi
	done < InpOutUg$num
((num++))
done
