#!/bin/bash 
#Create Gold Files
num=0
while [ $num -le 25 ] 
do

	credit=0
	index=1
	while read line;
	do
		if [ $index -eq 1 ]
		then 
			credit=$line
		elif [ $index -eq 2 ]
		then 
			state=$line
		elif [ $index -eq 3 ] 
		then
			level=$line
		fi
		((index++))
	done < ./Inputfolder/InpOutUg$num

	#echo $credit
	#echo $state
	#echo $level
	#echo "tuition" $tuition
	#echo "fee" $fee
	
	tuition=$(./$state$level  $credit)
	fee=$(./Fee$level  $credit)
	total=$(echo "$fee+$tuition" | bc)
	echo "$credit	$state	$level	$tuition	$fee	$total" > ./Goldfolder/GoldInpOutUg$num
	((num++))	
done
