#!/bin/bash

num=0
while [ $num -le 25 ]
do
#rm InpOutUg$num
	while read line;
	do	
	
		if [ "$line" = "In" ]
		then 
			echo "Out" >> InpOutUg$num
		else
			echo $line >> InpOutUg$num
		fi
	done < InpInUg$num
((num++))
done
