#!/bin/bash 
#Instate undergraduate (InUG)

index=0
credits=$1
default=171
if [ $credits -ge 19 ]
then echo $default
else
	for cost in 0 171 342 513 684 855 1026 1197 1368 1539 1710 1881 2052 2223 2394 2565 2736 2907 3078
	do
		if [ $index -eq $credits ];
		then echo $cost
		fi
		((index++))
	done
fi
